const MODULE_PREFIX = `TRANSLATION`;
export const START_JOB = `${MODULE_PREFIX}/START_JOB`;
export const STOP_JOB = `${MODULE_PREFIX}/STOP_JOB`;

export const FETCH_USER_SUCCESS = `${MODULE_PREFIX}/FETCH_USER_SUCCESS`;
export const SET_USER = `${MODULE_PREFIX}/SET_USER`;
export const SET_ORGANIZATION = `${MODULE_PREFIX}/SET_ORGANIZATION`;
export const SET_ORGANIZATION_USERS = `${MODULE_PREFIX}/SET_ORGANIZATION_USERS`;

export const SET_ORIGINAL_TRANSLATABLE_ARTICLE = `${MODULE_PREFIX}/SET_ORIGINAL_TRANSLATABLE_ARTICLE`;
export const SET_TRANSLATABLE_ARTICLE = `${MODULE_PREFIX}/SET_TRANSLATABLE_ARTICLE`;
export const SET_ORIGINAL_ARTICLE = `${MODULE_PREFIX}/SET_ORIGINAL_ARTICLE`;
export const SET_ORIGINAL_VIEWED_ARTICLE = `${MODULE_PREFIX}/SET_ORIGINAL_VIEWED_ARTICLE`;
export const SET_TEMP_VIEWED_ARTICLE = `${MODULE_PREFIX}/SET_TMP_VIEWED_ARTICLE`;

export const SET_CURRENT_SLIDE_INDEX = `${MODULE_PREFIX}/SET_CURRENT_SLIDE_INDEX`;
export const SET_CURRENT_SUBSLIDE_INDEX = `${MODULE_PREFIX}/SET_CURRENT_SUBSLIDE_INDEX`;
export const SET_CURRENT_EDITOR_INDEXES = `${MODULE_PREFIX}/SET_CURRENT_EDITOR_INDIXES`;

export const SET_TRANSLATION_RECORDING = `${MODULE_PREFIX}/SET_TRANSLATION_RECORDING`;
export const SET_RECORD_UPLOAD_LOADING = `${MODULE_PREFIX}/SET_RECORD_UPLOAD_LOADING`;

export const SET_EDITOR_PLAYING = `${MODULE_PREFIX}/SET_EDITOR_PLAYING`;
export const SET_EDITOR_MUTED = `${MODULE_PREFIX}/SET_EDITOR_MUTED`;

export const SET_PREVIEW = `${MODULE_PREFIX}/SET_PREVIEW`;

export const SET_SELECTED_SPEAKER_NUMBER = `${MODULE_PREFIX}/SET_SELECTED_SPEAKER_NUMBER`;

export const SET_TRANSLATION_EXPORTS = `${MODULE_PREFIX}/SET_TRANSLATION_EXPORTS`;
export const SET_LOADING = `${MODULE_PREFIX}/SET_LOADING`;
export const SET_ACTIVE_TAB_INDEX = `${MODULE_PREFIX}/SET_ACTIVE_TAB_INDEX`;

export const SET_EXPORT_HISTORY_CURRENT_PAGE_NUMBER = `${MODULE_PREFIX}/SET_EXPORT_HISTORY_CURRENT_PAGE_NUMBER`;
export const SET_EXPORT_HISTORY_TOTAL_PAGES = `${MODULE_PREFIX}/SET_EXPORT_HISTORY_TOTAL_PAGES`;
export const SET_SUBSLIDES = `${MODULE_PREFIX}/SET_SUBSLIDES`;

export const ADD_LOADING_SLIDE = `${MODULE_PREFIX}/ADD_LOADING_SLIDE`;
export const REMOVE_LOADING_SLIDe = `${MODULE_PREFIX}/REMOVE_LOADING_SLIDE`;

export const BATCH_UPDATE_STATE = `${MODULE_PREFIX}/BATCH_UPDATE_STATE`;

export const SET_SPEKAKER_TRANSLATION_ENDTIME_MODAL_VISIBLE = `${MODULE_PREFIX}/SET_SPEKAKER_TRANSLATION_ENDTIME_MODAL_VISIBLE`; 

export const SET_ARTICLE_BASE_LANGUAGES = `${MODULE_PREFIX}/SET_ARTICLE_BASE_LANGUAGES`;
export const SET_SELECTED_BASE_LANGUAGE = `${MODULE_PREFIX}/SET_SELECTED_BASE_LANGUAGE`;
export const SET_CC_VISIBLE = `${MODULE_PREFIX}/SET_CC_VISIBLE`;

export const SET_COMMENTS_VISIBLE = `${MODULE_PREFIX}/SET_COMMENTS_VISIBLE`;
export const SET_COMMENTS = `${MODULE_PREFIX}/SET_COMMENTS`;
export const SET_LIST_INDEX = `${MODULE_PREFIX}/SET_LIST_INDEX`;
export const SET_COMMENTS_SLIDES_INDEXES = `${MODULE_PREFIX}/SET_COMMENTS_SLIDES_INDEXES`;
export const SET_ADD_COMMENT_SLIDE_INDEX = `${MODULE_PREFIX}/SET_ADD_COMMENT_SLIDE_INDEX`;

export const SET_MAX_LIST_INDEX = `${MODULE_PREFIX}/SET_MAX_LIST_INDEX`;
export const SET_ADD_COMMENT_LOADING = `${MODULE_PREFIX}/SET_ADD_COMMENT_LOADING`;

export const SET_FIND_AND_REPLACE_MODAL_VISIBLE = `${MODULE_PREFIX}/SET_FIND_AND_REPLACE_MODAL_VISIBLE`;

export const SET_ARTICLE_VIDEO = `${MODULE_PREFIX}/SET_ARTICLE_VIDEO`;

export const SET_SYNC_ALL_LOADING = `${MODULE_PREFIX}/SET_SYNC_ALL_LOADING`;
// Subtitles tab
export const SET_SUBTITLES = `${MODULE_PREFIX}/SET_SUBTITLES`;
export const SET_SUBTITLES_UNDO_STACK = `${MODULE_PREFIX}/SET_SUBTITLES_UNDO_STACK`;
export const SET_SUBTITLES_REDO_STACK = `${MODULE_PREFIX}/SET_SUBTITLES_REDO_STACK`;
export const SET_SUBTITLES_LOADING = `${MODULE_PREFIX}/SET_SUBTITLES_LOADING`;
export const SET_SUBTITLES_VIDEO = `${MODULE_PREFIX}/SET_SUBTITLES_VIDEO`;
export const SET_SUBTITLES_TRANSLATION_EXPORT = `${MODULE_PREFIX}/SET_SUBTITLES_TRANSLATION_EXPORT`;
export const SET_SELECTED_SUBTITLE = `${MODULE_PREFIX}/SET_SELECTED_SUBTITLE`;
export const SET_SELECTED_SUBTITLE_INDEX = `${MODULE_PREFIX}/SET_SELECTED_SUBTITLE_INDEX`;
